name: Go Basic Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.7'
      - name: Go Version Check
        run: go version
