name: Go Basic Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.7'
      - name: Go Version Check
        run: go version
      - name: Download Go Test Script
        uses: Lowkh/GoSchoolTestScripts

